[settings]
lockfile = true

[tools]
# Keep in sync with:
# - web/Dockerfile (Node.js version)
# - web/package.json#packageManager (pnpm version)
node = "24.13.1"
pnpm = "10.29.3"
just = "1.46.0"
direnv = "2.37.1"
