export const REPORT_LIST_CACHE_TTL_MS = 5_000;
export const REPORT_SEARCH_CACHE_TTL_MS = 10_000;
export const REPORT_DETAIL_CACHE_TTL_MS = 60 * 60 * 1000;
export const REPORT_LIST_CACHE_MAX_ENTRIES = 100;
export const REPORT_DETAIL_CACHE_MAX_ENTRIES = 200;
